// Copyright (c) 2026 Piergiorgio Vagnozzi
// Licensed under the MIT License.

import 'package:flutter/material.dart';

class AppStrings {
  static const supportedLocales = <Locale>[
    Locale('en'),
    Locale('fr'),
    Locale('es'),
    Locale('pt'),
    Locale('de'),
    Locale('it'),
    Locale('nl'),
    Locale('ru'),
    Locale('ar'),
    Locale('he'),
    Locale('zh'),
    Locale('ja'),
    Locale('ko'),
  ];

  static const _values = <String, Map<String, String>>{
    'en': {
      'appTitle': 'ESP Tool Professional Demo',
      'subtitle': 'Protocol simulation and service showcase',
      'theme': 'Theme',
      'language': 'Language',
      'system': 'System',
      'light': 'Light',
      'dark': 'Dark',
      'serialPorts': 'Serial ports',
      'refreshPorts': 'Refresh ports',
      'noSerialPorts': 'No serial ports detected',
      'connect': 'Connect',
      'detectChip': 'Detect chip',
      'readMac': 'Read MAC',
      'flashInfo': 'Flash info',
      'writeFlash': 'Write flash',
      'eraseFlash': 'Erase flash',
      'readMd5': 'Read MD5',
      'ready': 'Ready',
      'logs': 'Execution log',
      'chip': 'Chip',
      'mac': 'MAC',
      'flash': 'Flash',
      'splash': 'Professional firmware toolkit'
    },
    'fr': {
      'appTitle': 'Démo Professionnelle ESP Tool',
      'subtitle': 'Simulation du protocole et démonstration des services',
      'theme': 'Thème',
      'language': 'Langue',
      'light': 'Clair',
      'dark': 'Sombre',
      'connect': 'Connecter',
      'detectChip': 'Détecter la puce',
      'readMac': 'Lire MAC',
      'flashInfo': 'Infos flash',
      'writeFlash': 'Écrire en flash',
      'eraseFlash': 'Effacer flash',
      'readMd5': 'Lire MD5',
      'ready': 'Prêt',
      'logs': 'Journal d’exécution',
      'chip': 'Puce',
      'mac': 'MAC',
      'flash': 'Flash',
      'splash': 'Boîte à outils firmware professionnelle'
    },
    'es': {
      'appTitle': 'Demo Profesional ESP Tool',
      'subtitle': 'Simulación del protocolo y demostración de servicios',
      'theme': 'Tema',
      'language': 'Idioma',
      'light': 'Claro',
      'dark': 'Oscuro',
      'connect': 'Conectar',
      'detectChip': 'Detectar chip',
      'readMac': 'Leer MAC',
      'flashInfo': 'Info flash',
      'writeFlash': 'Escribir flash',
      'eraseFlash': 'Borrar flash',
      'readMd5': 'Leer MD5',
      'ready': 'Listo',
      'logs': 'Registro de ejecución',
      'chip': 'Chip',
      'mac': 'MAC',
      'flash': 'Flash',
      'splash': 'Kit profesional de firmware'
    },
    'pt': {
      'appTitle': 'Demonstração Profissional ESP Tool',
      'subtitle': 'Simulação de protocolo e demonstração de serviços',
      'theme': 'Tema',
      'language': 'Idioma',
      'light': 'Claro',
      'dark': 'Escuro',
      'connect': 'Conectar',
      'detectChip': 'Detectar chip',
      'readMac': 'Ler MAC',
      'flashInfo': 'Info flash',
      'writeFlash': 'Gravar flash',
      'eraseFlash': 'Apagar flash',
      'readMd5': 'Ler MD5',
      'ready': 'Pronto',
      'logs': 'Log de execução',
      'chip': 'Chip',
      'mac': 'MAC',
      'flash': 'Flash',
      'splash': 'Kit profissional de firmware'
    },
    'de': {
      'appTitle': 'Professionelle ESP Tool Demo',
      'subtitle': 'Protokollsimulation und Service-Demonstration',
      'theme': 'Design',
      'language': 'Sprache',
      'light': 'Hell',
      'dark': 'Dunkel',
      'connect': 'Verbinden',
      'detectChip': 'Chip erkennen',
      'readMac': 'MAC lesen',
      'flashInfo': 'Flash-Info',
      'writeFlash': 'Flash schreiben',
      'eraseFlash': 'Flash löschen',
      'readMd5': 'MD5 lesen',
      'ready': 'Bereit',
      'logs': 'Ausführungsprotokoll',
      'chip': 'Chip',
      'mac': 'MAC',
      'flash': 'Flash',
      'splash': 'Professionelles Firmware-Toolkit'
    },
    'it': {
      'appTitle': 'Demo Professionale ESP Tool',
      'subtitle': 'Simulazione protocollo e showcase servizi',
      'theme': 'Tema',
      'language': 'Lingua',
      'light': 'Chiaro',
      'dark': 'Scuro',
      'connect': 'Connetti',
      'detectChip': 'Rileva chip',
      'readMac': 'Leggi MAC',
      'flashInfo': 'Info flash',
      'writeFlash': 'Scrivi flash',
      'eraseFlash': 'Cancella flash',
      'readMd5': 'Leggi MD5',
      'ready': 'Pronto',
      'logs': 'Log esecuzione',
      'chip': 'Chip',
      'mac': 'MAC',
      'flash': 'Flash',
      'splash': 'Toolkit firmware professionale'
    },
    'nl': {
      'appTitle': 'Professionele ESP Tool Demo',
      'subtitle': 'Protocols simulatie en serviceoverzicht',
      'theme': 'Thema',
      'language': 'Taal',
      'light': 'Licht',
      'dark': 'Donker',
      'connect': 'Verbinden',
      'detectChip': 'Chip detecteren',
      'readMac': 'MAC lezen',
      'flashInfo': 'Flash-info',
      'writeFlash': 'Flash schrijven',
      'eraseFlash': 'Flash wissen',
      'readMd5': 'MD5 lezen',
      'ready': 'Klaar',
      'logs': 'Uitvoeringslog',
      'chip': 'Chip',
      'mac': 'MAC',
      'flash': 'Flash',
      'splash': 'Professionele firmware toolkit'
    },
    'ru': {
      'appTitle': 'Профессиональная демо ESP Tool',
      'subtitle': 'Симуляция протокола и демонстрация сервисов',
      'theme': 'Тема',
      'language': 'Язык',
      'light': 'Светлая',
      'dark': 'Тёмная',
      'connect': 'Подключиться',
      'detectChip': 'Определить чип',
      'readMac': 'Считать MAC',
      'flashInfo': 'Инфо flash',
      'writeFlash': 'Записать flash',
      'eraseFlash': 'Стереть flash',
      'readMd5': 'Считать MD5',
      'ready': 'Готово',
      'logs': 'Журнал выполнения',
      'chip': 'Чип',
      'mac': 'MAC',
      'flash': 'Flash',
      'splash': 'Профессиональный набор прошивки'
    },
    'ar': {
      'appTitle': 'عرض احترافي لأداة ESP',
      'subtitle': 'محاكاة البروتوكول واستعراض الخدمات',
      'theme': 'السمة',
      'language': 'اللغة',
      'light': 'فاتح',
      'dark': 'داكن',
      'connect': 'اتصال',
      'detectChip': 'كشف الشريحة',
      'readMac': 'قراءة MAC',
      'flashInfo': 'معلومات الفلاش',
      'writeFlash': 'كتابة الفلاش',
      'eraseFlash': 'مسح الفلاش',
      'readMd5': 'قراءة MD5',
      'ready': 'جاهز',
      'logs': 'سجل التنفيذ',
      'chip': 'الشريحة',
      'mac': 'MAC',
      'flash': 'الفلاش',
      'splash': 'مجموعة أدوات احترافية للبرمجيات الثابتة'
    },
    'he': {
      'appTitle': 'הדגמה מקצועית ESP Tool',
      'subtitle': 'סימולציית פרוטוקול והדגמת שירותים',
      'theme': 'ערכת נושא',
      'language': 'שפה',
      'light': 'בהיר',
      'dark': 'כהה',
      'connect': 'התחבר',
      'detectChip': 'זיהוי שבב',
      'readMac': 'קריאת MAC',
      'flashInfo': 'מידע פלאש',
      'writeFlash': 'כתיבה לפלאש',
      'eraseFlash': 'מחיקת פלאש',
      'readMd5': 'קריאת MD5',
      'ready': 'מוכן',
      'logs': 'יומן ביצוע',
      'chip': 'שבב',
      'mac': 'MAC',
      'flash': 'פלאש',
      'splash': 'ערכת קושחה מקצועית'
    },
    'zh': {
      'appTitle': 'ESP Tool 专业演示',
      'subtitle': '协议模拟与服务展示',
      'theme': '主题',
      'language': '语言',
      'light': '浅色',
      'dark': '深色',
      'connect': '连接',
      'detectChip': '检测芯片',
      'readMac': '读取 MAC',
      'flashInfo': 'Flash 信息',
      'writeFlash': '写入 Flash',
      'eraseFlash': '擦除 Flash',
      'readMd5': '读取 MD5',
      'ready': '就绪',
      'logs': '执行日志',
      'chip': '芯片',
      'mac': 'MAC',
      'flash': 'Flash',
      'splash': '专业固件工具包'
    },
    'ja': {
      'appTitle': 'ESP Tool プロフェッショナルデモ',
      'subtitle': 'プロトコルシミュレーションとサービス紹介',
      'theme': 'テーマ',
      'language': '言語',
      'light': 'ライト',
      'dark': 'ダーク',
      'connect': '接続',
      'detectChip': 'チップ検出',
      'readMac': 'MAC 読み取り',
      'flashInfo': 'Flash 情報',
      'writeFlash': 'Flash 書き込み',
      'eraseFlash': 'Flash 消去',
      'readMd5': 'MD5 読み取り',
      'ready': '準備完了',
      'logs': '実行ログ',
      'chip': 'チップ',
      'mac': 'MAC',
      'flash': 'Flash',
      'splash': 'プロフェッショナルファームウェアツールキット'
    },
    'ko': {
      'appTitle': 'ESP Tool 전문가 데모',
      'subtitle': '프로토콜 시뮬레이션 및 서비스 시연',
      'theme': '테마',
      'language': '언어',
      'light': '라이트',
      'dark': '다크',
      'connect': '연결',
      'detectChip': '칩 감지',
      'readMac': 'MAC 읽기',
      'flashInfo': 'Flash 정보',
      'writeFlash': 'Flash 쓰기',
      'eraseFlash': 'Flash 지우기',
      'readMd5': 'MD5 읽기',
      'ready': '준비됨',
      'logs': '실행 로그',
      'chip': '칩',
      'mac': 'MAC',
      'flash': 'Flash',
      'splash': '전문 펌웨어 툴킷'
    }
  };

  static const _languageDisplayNames = <String, String>{
    'en': 'English',
    'fr': 'Français',
    'es': 'Español',
    'pt': 'Português',
    'de': 'Deutsch',
    'it': 'Italiano',
    'nl': 'Nederlands',
    'ru': 'Русский',
    'ar': 'العربية',
    'he': 'עברית',
    'zh': '中文',
    'ja': '日本語',
    'ko': '한국어',
  };

  static const _languageFlags = <String, String>{
    'en': '\u{1F1EC}\u{1F1E7}',
    'fr': '\u{1F1EB}\u{1F1F7}',
    'es': '\u{1F1EA}\u{1F1F8}',
    'pt': '\u{1F1F5}\u{1F1F9}',
    'de': '\u{1F1E9}\u{1F1EA}',
    'it': '\u{1F1EE}\u{1F1F9}',
    'nl': '\u{1F1F3}\u{1F1F1}',
    'ru': '\u{1F1F7}\u{1F1FA}',
    'ar': '\u{1F1F8}\u{1F1E6}',
    'he': '\u{1F1EE}\u{1F1F1}',
    'zh': '\u{1F1E8}\u{1F1F3}',
    'ja': '\u{1F1EF}\u{1F1F5}',
    'ko': '\u{1F1F0}\u{1F1F7}',
  };

  static String t(Locale locale, String key) {
    final lang = _values[locale.languageCode] ?? _values['en']!;
    return lang[key] ?? _values['en']![key] ?? key;
  }

  static String languageDisplayName(Locale locale) =>
      _languageDisplayNames[locale.languageCode] ?? _languageDisplayNames['en']!;

  static String languageFlag(Locale locale) =>
      _languageFlags[locale.languageCode] ?? '🏳️';
}
