name: esptool_ui
description: Professional demo app for flutter_esptool package capabilities.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_esptool:
    path: ../..
  platform_serial: ^0.1.0
  file_selector: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^3.0.0

dependency_overrides:
  platform_serial:
    path: ../../third_party/platform_serial

flutter:
  uses-material-design: true
  assets:
    - assets/flags/
