// Copyright (c) 2026 Piergiorgio Vagnozzi
// Licensed under the MIT License.

import 'package:flutter/material.dart';

class AppStrings {
  static const supportedLocales = <Locale>[
    Locale('en'),
    Locale('fr'),
    Locale('es'),
    Locale('pt'),
    Locale('de'),
    Locale('it'),
    Locale('nl'),
    Locale('ru'),
    Locale('ar'),
    Locale('he'),
    Locale('zh'),
    Locale('ja'),
    Locale('ko'),
  ];

  static const _values = <String, Map<String, String>>{
    'en': {
      'appTitle': 'ESP Tool Professional Demo',
      'subtitle': 'Live serial workflow for ESP devices',
      'theme': 'Theme',
      'language': 'Language',
      'system': 'System',
      'light': 'Light',
      'dark': 'Dark',
      'serialPorts': 'Serial ports',
      'refreshPorts': 'Refresh ports',
      'noSerialPorts': 'No serial ports detected',
      'serialUnavailable': 'Serial interface unavailable',
      'serialPluginUnavailable':
          'Serial plugin unavailable. Run on a supported target.',
      'selectSerialPort': 'Select a serial port before connecting',
      'sampleFlashNotice':
          'Using the built-in sample image for this write operation',
      'connect': 'Connect',
      'detectChip': 'Detect chip',
      'readMac': 'Read MAC',
      'flashInfo': 'Flash info',
      'writeFlash': 'Write flash',
      'eraseFlash': 'Erase flash',
      'readMd5': 'Read MD5',
      'ready': 'Ready',
      'logs': 'Execution log',
      'chip': 'Chip',
      'mac': 'MAC',
      'flash': 'Flash',
      'splash': 'Professional firmware toolkit'
    },
    'fr': {
      'appTitle': 'Démo Professionnelle ESP Tool',
      'subtitle': 'Flux série réel pour appareils ESP',
      'theme': 'Thème',
      'language': 'Langue',
      'light': 'Clair',
      'dark': 'Sombre',
      'connect': 'Connecter',
      'detectChip': 'Détecter la puce',
      'readMac': 'Lire MAC',
      'flashInfo': 'Infos flash',
      'writeFlash': 'Écrire en flash',
      'eraseFlash': 'Effacer flash',
      'readMd5': 'Lire MD5',
      'ready': 'Prêt',
      'logs': 'Journal d’exécution',
      'chip': 'Puce',
      'mac': 'MAC',
      'flash': 'Flash',
      'splash': 'Boîte à outils firmware professionnelle'
    },
    'es': {
      'appTitle': 'Demo Profesional ESP Tool',
      'subtitle': 'Flujo serie real para dispositivos ESP',
      'theme': 'Tema',
      'language': 'Idioma',
      'light': 'Claro',
      'dark': 'Oscuro',
      'connect': 'Conectar',
      'detectChip': 'Detectar chip',
      'readMac': 'Leer MAC',
      'flashInfo': 'Info flash',
      'writeFlash': 'Escribir flash',
      'eraseFlash': 'Borrar flash',
      'readMd5': 'Leer MD5',
      'ready': 'Listo',
      'logs': 'Registro de ejecución',
      'chip': 'Chip',
      'mac': 'MAC',
      'flash': 'Flash',
      'splash': 'Kit profesional de firmware'
    },
    'pt': {
      'appTitle': 'Demonstração Profissional ESP Tool',
      'subtitle': 'Fluxo serial real para dispositivos ESP',
      'theme': 'Tema',
      'language': 'Idioma',
      'light': 'Claro',
      'dark': 'Escuro',
      'connect': 'Conectar',
      'detectChip': 'Detectar chip',
      'readMac': 'Ler MAC',
      'flashInfo': 'Info flash',
      'writeFlash': 'Gravar flash',
      'eraseFlash': 'Apagar flash',
      'readMd5': 'Ler MD5',
      'ready': 'Pronto',
      'logs': 'Log de execução',
      'chip': 'Chip',
      'mac': 'MAC',
      'flash': 'Flash',
      'splash': 'Kit profissional de firmware'
    },
    'de': {
      'appTitle': 'Professionelle ESP Tool Demo',
      'subtitle': 'Echter Seriell-Workflow für ESP-Geräte',
      'theme': 'Design',
      'language': 'Sprache',
      'light': 'Hell',
      'dark': 'Dunkel',
      'connect': 'Verbinden',
      'detectChip': 'Chip erkennen',
      'readMac': 'MAC lesen',
      'flashInfo': 'Flash-Info',
      'writeFlash': 'Flash schreiben',
      'eraseFlash': 'Flash löschen',
      'readMd5': 'MD5 lesen',
      'ready': 'Bereit',
      'logs': 'Ausführungsprotokoll',
      'chip': 'Chip',
      'mac': 'MAC',
      'flash': 'Flash',
      'splash': 'Professionelles Firmware-Toolkit'
    },
    'it': {
      'appTitle': 'Demo Professionale ESP Tool',
      'subtitle': 'Flusso seriale reale per dispositivi ESP',
      'theme': 'Tema',
      'language': 'Lingua',
      'light': 'Chiaro',
      'dark': 'Scuro',
      'connect': 'Connetti',
      'detectChip': 'Rileva chip',
      'readMac': 'Leggi MAC',
      'flashInfo': 'Info flash',
      'writeFlash': 'Scrivi flash',
      'eraseFlash': 'Cancella flash',
      'readMd5': 'Leggi MD5',
      'ready': 'Pronto',
      'logs': 'Log esecuzione',
      'chip': 'Chip',
      'mac': 'MAC',
      'flash': 'Flash',
      'splash': 'Toolkit firmware professionale'
    },
    'nl': {
      'appTitle': 'Professionele ESP Tool Demo',
      'subtitle': 'Echte seriële workflow voor ESP-apparaten',
      'theme': 'Thema',
      'language': 'Taal',
      'light': 'Licht',
      'dark': 'Donker',
      'connect': 'Verbinden',
      'detectChip': 'Chip detecteren',
      'readMac': 'MAC lezen',
      'flashInfo': 'Flash-info',
      'writeFlash': 'Flash schrijven',
      'eraseFlash': 'Flash wissen',
      'readMd5': 'MD5 lezen',
      'ready': 'Klaar',
      'logs': 'Uitvoeringslog',
      'chip': 'Chip',
      'mac': 'MAC',
      'flash': 'Flash',
      'splash': 'Professionele firmware toolkit'
    },
    'ru': {
      'appTitle': 'Профессиональная демо ESP Tool',
      'subtitle': 'Реальный последовательный интерфейс для устройств ESP',
      'theme': 'Тема',
      'language': 'Язык',
      'light': 'Светлая',
      'dark': 'Тёмная',
      'connect': 'Подключиться',
      'detectChip': 'Определить чип',
      'readMac': 'Считать MAC',
      'flashInfo': 'Инфо flash',
      'writeFlash': 'Записать flash',
      'eraseFlash': 'Стереть flash',
      'readMd5': 'Считать MD5',
      'ready': 'Готово',
      'logs': 'Журнал выполнения',
      'chip': 'Чип',
      'mac': 'MAC',
      'flash': 'Flash',
      'splash': 'Профессиональный набор прошивки'
    },
    'ar': {
      'appTitle': 'عرض احترافي لأداة ESP',
      'subtitle': 'تدفق تسلسلي فعلي لأجهزة ESP',
      'theme': 'السمة',
      'language': 'اللغة',
      'light': 'فاتح',
      'dark': 'داكن',
      'connect': 'اتصال',
      'detectChip': 'كشف الشريحة',
      'readMac': 'قراءة MAC',
      'flashInfo': 'معلومات الفلاش',
      'writeFlash': 'كتابة الفلاش',
      'eraseFlash': 'مسح الفلاش',
      'readMd5': 'قراءة MD5',
      'ready': 'جاهز',
      'logs': 'سجل التنفيذ',
      'chip': 'الشريحة',
      'mac': 'MAC',
      'flash': 'الفلاش',
      'splash': 'مجموعة أدوات احترافية للبرمجيات الثابتة'
    },
    'he': {
      'appTitle': 'הדגמה מקצועית ESP Tool',
      'subtitle': 'תהליך טורי אמיתי עבור התקני ESP',
      'theme': 'ערכת נושא',
      'language': 'שפה',
      'light': 'בהיר',
      'dark': 'כהה',
      'connect': 'התחבר',
      'detectChip': 'זיהוי שבב',
      'readMac': 'קריאת MAC',
      'flashInfo': 'מידע פלאש',
      'writeFlash': 'כתיבה לפלאש',
      'eraseFlash': 'מחיקת פלאש',
      'readMd5': 'קריאת MD5',
      'ready': 'מוכן',
      'logs': 'יומן ביצוע',
      'chip': 'שבב',
      'mac': 'MAC',
      'flash': 'פלאש',
      'splash': 'ערכת קושחה מקצועית'
    },
    'zh': {
      'appTitle': 'ESP Tool 专业演示',
      'subtitle': '面向 ESP 设备的真实串口流程',
      'theme': '主题',
      'language': '语言',
      'light': '浅色',
      'dark': '深色',
      'connect': '连接',
      'detectChip': '检测芯片',
      'readMac': '读取 MAC',
      'flashInfo': 'Flash 信息',
      'writeFlash': '写入 Flash',
      'eraseFlash': '擦除 Flash',
      'readMd5': '读取 MD5',
      'ready': '就绪',
      'logs': '执行日志',
      'chip': '芯片',
      'mac': 'MAC',
      'flash': 'Flash',
      'splash': '专业固件工具包'
    },
    'ja': {
      'appTitle': 'ESP Tool プロフェッショナルデモ',
      'subtitle': 'ESP デバイス向けの実シリアルワークフロー',
      'theme': 'テーマ',
      'language': '言語',
      'light': 'ライト',
      'dark': 'ダーク',
      'connect': '接続',
      'detectChip': 'チップ検出',
      'readMac': 'MAC 読み取り',
      'flashInfo': 'Flash 情報',
      'writeFlash': 'Flash 書き込み',
      'eraseFlash': 'Flash 消去',
      'readMd5': 'MD5 読み取り',
      'ready': '準備完了',
      'logs': '実行ログ',
      'chip': 'チップ',
      'mac': 'MAC',
      'flash': 'Flash',
      'splash': 'プロフェッショナルファームウェアツールキット'
    },
    'ko': {
      'appTitle': 'ESP Tool 전문가 데모',
      'subtitle': 'ESP 장치를 위한 실제 시리얼 워크플로',
      'theme': '테마',
      'language': '언어',
      'light': '라이트',
      'dark': '다크',
      'connect': '연결',
      'detectChip': '칩 감지',
      'readMac': 'MAC 읽기',
      'flashInfo': 'Flash 정보',
      'writeFlash': 'Flash 쓰기',
      'eraseFlash': 'Flash 지우기',
      'readMd5': 'MD5 읽기',
      'ready': '준비됨',
      'logs': '실행 로그',
      'chip': '칩',
      'mac': 'MAC',
      'flash': 'Flash',
      'splash': '전문 펌웨어 툴킷'
    }
  };

  static const _languageDisplayNames = <String, String>{
    'en': 'English',
    'fr': 'Français',
    'es': 'Español',
    'pt': 'Português',
    'de': 'Deutsch',
    'it': 'Italiano',
    'nl': 'Nederlands',
    'ru': 'Русский',
    'ar': 'العربية',
    'he': 'עברית',
    'zh': '中文',
    'ja': '日本語',
    'ko': '한국어',
  };

  static const _languageFlagAssets = <String, String>{
    'en': 'assets/flags/en.png',
    'fr': 'assets/flags/fr.png',
    'es': 'assets/flags/es.png',
    'pt': 'assets/flags/pt.png',
    'de': 'assets/flags/de.png',
    'it': 'assets/flags/it.png',
    'nl': 'assets/flags/nl.png',
    'ru': 'assets/flags/ru.png',
    'ar': 'assets/flags/ar.png',
    'he': 'assets/flags/he.png',
    'zh': 'assets/flags/zh.png',
    'ja': 'assets/flags/ja.png',
    'ko': 'assets/flags/ko.png',
  };

  static String t(Locale locale, String key) {
    final lang = _values[locale.languageCode] ?? _values['en']!;
    return lang[key] ?? _values['en']![key] ?? key;
  }

  static String languageDisplayName(Locale locale) =>
      _languageDisplayNames[locale.languageCode] ?? _languageDisplayNames['en']!;

  static String languageFlagAsset(Locale locale) =>
      _languageFlagAssets[locale.languageCode] ?? 'assets/flags/en.png';
}
