name: esptool_cli
description: A complete CLI tool for ESP chip programming - clone of official esptool
publish_to: none

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_esptool:
    path: ../../
  args: ^2.4.0

  meta: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mocktail: ^1.0.0

dependency_overrides:
  platform_serial:
    path: ../../third_party/platform_serial
