name: esptool_cli
description: A complete CLI tool for ESP chip programming - clone of official esptool
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter_esptool:
    path: ../../
  args: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mocktail: ^1.0.0
