name: PR Labeler

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - dev
      - test
      - stable
      - main

permissions:
  pull-requests: write
  contents: read

jobs:
  label:
    name: Label PR
    runs-on: ubuntu-latest
    steps:
      - name: Apply labels
        uses: actions/labeler@v5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/labeler.yml
